services:
  - type: web
    name: blood-donation-app
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: core
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blood-donation-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_HOSTS
        sync: false
    autoDeploy: true

databases:
  - name: blood-donation-db
    databaseName: neondb
    user: neondb_owner
    plan: free
    region: oregon
